<?php
/**
 * Created by PhpStorm.
 * User: yorun
 * Date: 2017/2/22
 * Time: 20:52
 */

namespace app\models;


use yii\base\Model;

class HouseSelect extends Model
{

    public $CELL_ID;
    public $BUILD_ID;
    public $HOUSE_ID;
    public $KEY;

    public function rules()
    {
        return [
            [['BUILD_ID', 'CELL_ID', 'HOUSE_ID'], 'integer'],
            [['KEY',], 'string'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'CELL_ID' => '小区',
            'BUILD_ID' => '楼宇',
            'HOUSE_ID' => '房屋',
            'KEY' => '关键字（姓名，手机，身份证）',
            
        ]; // TODO: Change the autogenerated stub
    }

}